"""replace side image with right left images

Revision ID: 0f05255b6f9a
Revises: ec728edcfd3b
Create Date: 2026-03-10 19:25:51.950909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f05255b6f9a'
down_revision = 'ec728edcfd3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('branding_specs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('right_image_path', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('left_image_path', sa.String(length=500), nullable=True))
        batch_op.drop_column('side_image_path')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('branding_specs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('side_image_path', sa.VARCHAR(length=500), nullable=True))
        batch_op.drop_column('left_image_path')
        batch_op.drop_column('right_image_path')

    # ### end Alembic commands ###
