"""product config workflow and customer requests

Revision ID: bdac138222e7
Revises: 0f05255b6f9a
Create Date: 2026-03-10 19:41:32.125885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdac138222e7'
down_revision = '0f05255b6f9a'
branch_labels = None
depends_on = None


def upgrade():
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    tables = inspector.get_table_names()

    if "customer_requests" not in tables:
        op.create_table(
            "customer_requests",
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("customer_name", sa.String(length=255), nullable=False),
            sa.Column("team_name", sa.String(length=255), nullable=True),
            sa.Column("email", sa.String(length=255), nullable=True),
            sa.Column("mobile", sa.String(length=40), nullable=True),
            sa.Column("requested_products", sa.Text(), nullable=False),
            sa.Column("notes", sa.Text(), nullable=True),
            sa.Column("roster_csv_path", sa.String(length=500), nullable=True),
            sa.Column("created_at", sa.DateTime(), nullable=False),
            sa.Column("updated_at", sa.DateTime(), nullable=False),
            sa.PrimaryKeyConstraint("id"),
        )

    branding_cols = {c["name"] for c in inspector.get_columns("branding_specs")}
    with op.batch_alter_table('branding_specs', schema=None) as batch_op:
        if "order_item_id" not in branding_cols:
            batch_op.add_column(sa.Column("order_item_id", sa.Integer(), nullable=True))
        if "gender" not in branding_cols:
            batch_op.add_column(sa.Column("gender", sa.String(length=20), nullable=True))
        if "sleeve_type" not in branding_cols:
            batch_op.add_column(sa.Column("sleeve_type", sa.String(length=10), nullable=True))
        if bind.dialect.name != "sqlite":
            batch_op.create_unique_constraint("uq_branding_specs_order_item_id", ["order_item_id"])
            batch_op.create_foreign_key(
                "fk_branding_specs_order_item_id_order_items",
                "order_items",
                ["order_item_id"],
                ["id"],
            )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('branding_specs', schema=None) as batch_op:
        batch_op.drop_constraint('fk_branding_specs_order_item_id_order_items', type_='foreignkey')
        batch_op.drop_constraint('uq_branding_specs_order_item_id', type_='unique')
        batch_op.drop_column('sleeve_type')
        batch_op.drop_column('gender')
        batch_op.drop_column('order_item_id')

    op.drop_table('customer_requests')
    # ### end Alembic commands ###
