"""add branding media columns

Revision ID: ec728edcfd3b
Revises: 9ec754499a64
Create Date: 2026-03-10 19:07:53.854573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec728edcfd3b'
down_revision = '9ec754499a64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('branding_specs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('front_image_path', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('back_image_path', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('side_image_path', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('logo_positions', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('logo_right_path', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('logo_left_path', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('logo_front_path', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('logo_back_path', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('branding_specs', schema=None) as batch_op:
        batch_op.drop_column('logo_back_path')
        batch_op.drop_column('logo_front_path')
        batch_op.drop_column('logo_left_path')
        batch_op.drop_column('logo_right_path')
        batch_op.drop_column('logo_positions')
        batch_op.drop_column('side_image_path')
        batch_op.drop_column('back_image_path')
        batch_op.drop_column('front_image_path')

    # ### end Alembic commands ###
